// src/admin/components/TimeRangeSlider.tsx
import React, { useEffect, useRef, useCallback, useState } from 'react';
import { Box, ToggleButton, ToggleButtonGroup, Typography, Skeleton } from '@mui/material';
import noUiSlider, { type API as SliderAPI } from 'nouislider';
import 'nouislider/dist/nouislider.css';
import {
  TIME_RANGE_PRESETS,
  formatDuration,
  formatDateTimeFull,
  formatDateShort,
  resolveAggregation,
} from '../utils/timeRange';
import { tokens } from '../theme';

interface TimeRangeSliderProps {
  /** Earliest available data timestamp (ms since epoch) */
  dataMin: number;
  /** Latest available data timestamp (ms since epoch) */
  dataMax: number;
  /** Whether the data range is still loading */
  loading?: boolean;
  /** Current start timestamp (ms since epoch) */
  start: number;
  /** Current end timestamp (ms since epoch) */
  end: number;
  /** Called when the user changes the range via slider or quick button */
  onChange: (start: number, end: number) => void;
  /** Which quick-select buttons to show. Default: ['24h', '7d', '30d'] */
  presets?: string[];
  /** noUiSlider step in ms. Default: 600000 (10 minutes) */
  step?: number;
  /** Compact mode (less vertical space, for ParameterChart headers). Default: false */
  compact?: boolean;
}

const SLIDER_CSS = `
.trs-slider .noUi-target {
  background: ${tokens.brand.bg};
  border: 1px solid ${tokens.brand.divider};
  box-shadow: none;
  height: 8px;
}
.trs-slider .noUi-connect {
  background: ${tokens.brand.primary};
}
.trs-slider .noUi-handle {
  border: 2px solid ${tokens.brand.primary};
  background: ${tokens.brand.surface};
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  width: 18px !important;
  height: 18px !important;
  right: -9px !important;
  top: -6px !important;
  border-radius: 50%;
  cursor: grab;
}
.trs-slider .noUi-handle:before,
.trs-slider .noUi-handle:after {
  display: none;
}
.trs-slider .noUi-tooltip {
  font-size: 0.65rem;
  padding: 2px 6px;
  background: ${tokens.brand.text};
  color: ${tokens.brand.surface};
  border: none;
  border-radius: 4px;
  white-space: nowrap;
}
.trs-slider .noUi-pips-horizontal {
  padding-top: 6px;
  height: 40px;
}
.trs-slider .noUi-value-horizontal {
  transform: translateX(-50%);
  font-size: 0.6rem;
  color: ${tokens.brand.textMuted};
}
.trs-slider .noUi-marker-horizontal.noUi-marker-large {
  height: 8px;
  background: ${tokens.brand.divider};
}
.trs-slider-compact .noUi-target {
  height: 6px;
}
.trs-slider-compact .noUi-handle {
  width: 14px !important;
  height: 14px !important;
  right: -7px !important;
  top: -5px !important;
}
`;

export const TimeRangeSlider: React.FC<TimeRangeSliderProps> = ({
  dataMin,
  dataMax,
  loading = false,
  start,
  end,
  onChange,
  presets = ['24h', '7d', '30d'],
  step = 600000,
  compact = false,
}) => {
  const sliderElRef = useRef<HTMLDivElement>(null);
  const sliderRef = useRef<SliderAPI | null>(null);
  const styleInjected = useRef(false);
  // Local span for smooth info-text updates during drag (avoids waiting for React re-render)
  const [liveSpanMs, setLiveSpanMs] = useState<number | null>(null);

  // Inject CSS once
  useEffect(() => {
    if (styleInjected.current) return;
    styleInjected.current = true;
    const style = document.createElement('style');
    style.textContent = SLIDER_CSS;
    document.head.appendChild(style);
    return () => { document.head.removeChild(style); };
  }, []);

  // Determine which preset is active (if any)
  const activePreset = (() => {
    if (!dataMax) return null;
    for (const key of presets) {
      const ms = TIME_RANGE_PRESETS[key];
      if (!ms) continue;
      const expectedStart = Math.max(dataMin, dataMax - ms);
      // Allow 1-step tolerance for snapping
      if (Math.abs(start - expectedStart) <= step && Math.abs(end - dataMax) <= step) {
        return key;
      }
    }
    return null;
  })();

  const handlePreset = useCallback(
    (_: React.MouseEvent, value: string | null) => {
      if (!value || !dataMax) return;
      const ms = TIME_RANGE_PRESETS[value];
      if (!ms) return;
      const newStart = Math.max(dataMin, dataMax - ms);
      onChange(newStart, dataMax);
    },
    [dataMin, dataMax, onChange],
  );

  // Create / recreate slider when data range changes
  useEffect(() => {
    const el = sliderElRef.current;
    if (!el || !dataMin || !dataMax || dataMin >= dataMax) return;

    // Destroy existing
    if (sliderRef.current) {
      sliderRef.current.destroy();
      sliderRef.current = null;
    }

    const rangeDays = (dataMax - dataMin) / 86400000;
    const oneDayMs = 86400000;
    const oneWeekMs = 7 * oneDayMs;
    const todayStart = dataMax - oneDayMs;
    const weekStart = dataMax - oneWeekMs;

    // Build non-linear range for longer datasets
    let sliderRange: { min: number; max: number; [key: string]: number };
    let pipsConfig: any;

    if (!compact) {
      if (rangeDays > 8) {
        sliderRange = { min: dataMin, '50%': weekStart, '80%': todayStart, max: dataMax };
        pipsConfig = {
          mode: 'positions' as const,
          values: [0, 25, 50, 65, 80, 90, 100],
          density: 100,
          format: {
            to: (v: number) => {
              const hoursFromEnd = (dataMax - v) / 3600000;
              if (hoursFromEnd <= 24) {
                const h = new Date(v).getHours();
                if (h === 0) return formatDateShort(v);
                if (h === 6 || h === 12 || h === 18) return h + ':00';
                return '';
              }
              return formatDateShort(v);
            },
          },
        };
      } else if (rangeDays > 2) {
        sliderRange = { min: dataMin, '70%': todayStart, max: dataMax };
        pipsConfig = {
          mode: 'positions' as const,
          values: [0, 20, 40, 60, 85, 100],
          format: {
            to: (v: number) => {
              const hoursFromEnd = (dataMax - v) / 3600000;
              if (hoursFromEnd <= 24) {
                const h = new Date(v).getHours();
                if (h === 0) return formatDateShort(v);
                if (h === 12) return '12:00';
                return '';
              }
              return formatDateShort(v);
            },
          },
        };
      } else {
        sliderRange = { min: dataMin, max: dataMax };
        pipsConfig = {
          mode: 'count' as const,
          values: 6,
          format: {
            to: (v: number) => {
              if (rangeDays < 1) {
                return new Date(v).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
              }
              return formatDateShort(v);
            },
          },
        };
      }
    } else {
      sliderRange = { min: dataMin, max: dataMax };
      pipsConfig = false;
    }

    const clampedStart = Math.max(dataMin, Math.min(start, dataMax));
    const clampedEnd = Math.max(dataMin, Math.min(end, dataMax));

    const slider = noUiSlider.create(el, {
      start: [clampedStart, clampedEnd],
      connect: true,
      range: sliderRange,
      step,
      tooltips: [
        { to: (v: number) => formatDateTimeFull(v) },
        { to: (v: number) => formatDateTimeFull(v) },
      ],
      pips: pipsConfig || undefined,
    });

    // 'slide' fires only on user interaction (NOT on programmatic set()),
    // so there's no feedback loop with the sync effect below.
    // Update local span immediately for smooth info-text, and propagate to parent.
    slider.on('slide', (values: (string | number)[]) => {
      const s = Number(values[0]);
      const e = Number(values[1]);
      setLiveSpanMs(e - s);
      onChange(s, e);
    });

    // Clear live span override when the user releases the handle
    slider.on('change', () => {
      setLiveSpanMs(null);
    });

    // Prevent text selection during drag
    el.addEventListener('dragstart', (ev) => ev.preventDefault());
    el.addEventListener('selectstart', (ev) => ev.preventDefault());

    sliderRef.current = slider;

    return () => {
      slider.destroy();
      sliderRef.current = null;
    };
  }, [dataMin, dataMax, compact, step]);

  // Sync slider handles when start/end props change (from quick buttons or parent).
  // Since we use 'slide' (not 'update'), programmatic set() won't re-trigger onChange.
  useEffect(() => {
    const slider = sliderRef.current;
    if (!slider) return;

    const clampedStart = Math.max(dataMin, Math.min(start, dataMax));
    const clampedEnd = Math.max(dataMin, Math.min(end, dataMax));

    // Skip if slider is already at the target position (avoids unnecessary DOM work during drag)
    const current = slider.get() as string[];
    if (Math.abs(Number(current[0]) - clampedStart) < 1 && Math.abs(Number(current[1]) - clampedEnd) < 1) return;

    slider.set([clampedStart, clampedEnd]);
  }, [start, end, dataMin, dataMax]);

  const spanMs = liveSpanMs ?? (end - start);
  const resolution = resolveAggregation(spanMs);
  const rangeDays = dataMax && dataMin ? (dataMax - dataMin) / 86400000 : 0;

  // Timeline legend zone widths
  const zones = (() => {
    if (compact || rangeDays <= 2) return null;
    if (rangeDays > 8) {
      return [
        { width: '50%', color: tokens.brand.textMuted, label: 'History' },
        { width: '30%', color: tokens.brand.primary, label: 'Last week' },
        { width: '20%', color: tokens.severity.ok.main, label: 'Last day' },
      ];
    }
    return [
      { width: '70%', color: tokens.brand.primary, label: 'This week' },
      { width: '30%', color: tokens.severity.ok.main, label: 'Last day' },
    ];
  })();

  if (loading) {
    return (
      <Box sx={{ width: '100%', py: compact ? 0.5 : 1 }}>
        <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mb: 1 }}>
          {presets.map((p) => (
            <Skeleton key={p} variant="rounded" width={40} height={28} />
          ))}
        </Box>
        <Skeleton variant="rounded" height={compact ? 20 : 50} />
      </Box>
    );
  }

  if (!dataMin || !dataMax || dataMin >= dataMax) {
    return null;
  }

  return (
    <Box
      className={`trs-slider ${compact ? 'trs-slider-compact' : ''}`}
      sx={{ width: '100%', py: compact ? 0.5 : 1 }}
      onClick={(e) => e.stopPropagation()}
    >
      {/* Quick-select buttons */}
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mb: compact ? 0.5 : 1 }}>
        <ToggleButtonGroup
          value={activePreset}
          exclusive
          onChange={handlePreset}
          size="small"
        >
          {presets.map((p) => (
            <ToggleButton key={p} value={p} sx={{ fontSize: '0.75rem', py: 0.25, px: 1 }}>
              {p}
            </ToggleButton>
          ))}
        </ToggleButtonGroup>
        <Typography variant="caption" color="text.secondary" sx={{ ml: 'auto' }}>
          {formatDuration(spanMs)}
          {!compact && (
            <Typography component="span" variant="caption" sx={{ ml: 1, fontStyle: 'italic', color: 'text.disabled' }}>
              ({resolution === 'raw' ? 'raw' : `${resolution} avg`})
            </Typography>
          )}
        </Typography>
      </Box>

      {/* Slider */}
      <Box sx={{ px: compact ? 0 : 0.5 }}>
        <div ref={sliderElRef} />
      </Box>

      {/* Timeline legend zones (non-compact only) */}
      {zones && (
        <>
          <Box
            sx={{
              display: 'flex',
              height: 6,
              borderRadius: '3px',
              overflow: 'hidden',
              mt: 2,
              mx: 0.5,
            }}
          >
            {zones.map((zone, i) => (
              <Box
                key={i}
                sx={{
                  width: zone.width,
                  height: '100%',
                  backgroundColor: zone.color,
                  position: 'relative',
                  '&:not(:last-child)::after': {
                    content: '""',
                    position: 'absolute',
                    right: 0,
                    top: -2,
                    height: 10,
                    width: 1,
                    backgroundColor: tokens.brand.text,
                    opacity: 0.3,
                  },
                }}
              />
            ))}
          </Box>
          <Box sx={{ display: 'flex', mx: 0.5, mt: 0.25 }}>
            {zones.map((zone, i) => (
              <Typography
                key={i}
                variant="caption"
                sx={{
                  width: zone.width,
                  textAlign: 'center',
                  fontSize: '0.6rem',
                  color: zone.color,
                  opacity: 0.7,
                }}
              >
                {zone.label}
              </Typography>
            ))}
          </Box>
        </>
      )}
    </Box>
  );
};

// src/lib/components/charts/TimeRangeSlider.svelte
<script lang="ts">
	import { onDestroy } from 'svelte';
	import noUiSlider, { PipsMode, type API, type Options } from 'nouislider';
	import 'nouislider/dist/nouislider.css';
	import { tokens } from '$lib/charts/tokens';

	let {
		min,
		max,
		start = $bindable<number>(0),
		end = $bindable<number>(0),
		onchange,
	}: {
		min: number;
		max: number;
		start: number;
		end: number;
		onchange?: (start: number, end: number) => void;
	} = $props();

	let el: HTMLDivElement;
	let slider: API | null = null;
	let suppressUpdate = false;

	const rangeDays = $derived((max - min) / 86400000);
	const todayStart = $derived(new Date(new Date(max).setUTCHours(0, 0, 0, 0)).getTime());
	const weekStart = $derived(todayStart - 7 * 86400000);

	// Matching the React dashboard: grey (history), blue (week), green (today)
	// Light versions for track background, full for labels
	const COL_HISTORY = tokens.brand.textMuted;
	const COL_WEEK = tokens.brand.primary;
	const COL_TODAY = tokens.severity.ok.main;
	const COL_HISTORY_LIGHT = 'rgba(90,100,114,0.25)';
	const COL_WEEK_LIGHT = 'rgba(31,78,121,0.30)';
	const COL_TODAY_LIGHT = 'rgba(46,125,50,0.30)';

	const zones = $derived.by(() => {
		if (rangeDays > 8) {
			return [
				{ label: 'History', width: '50%', color: COL_HISTORY },
				{ label: 'Last week', width: '30%', color: COL_WEEK },
				{ label: 'Today', width: '20%', color: COL_TODAY },
			];
		} else if (rangeDays > 2) {
			return [
				{ label: 'This week', width: '70%', color: COL_WEEK },
				{ label: 'Today', width: '30%', color: COL_TODAY },
			];
		} else {
			return [{ label: 'All data', width: '100%', color: COL_WEEK }];
		}
	});

	const trackGradient = $derived.by(() => {
		if (rangeDays > 8) {
			return `linear-gradient(to right, ${COL_HISTORY_LIGHT} 0%, ${COL_HISTORY_LIGHT} 50%, ${COL_WEEK_LIGHT} 50%, ${COL_WEEK_LIGHT} 80%, ${COL_TODAY_LIGHT} 80%, ${COL_TODAY_LIGHT} 100%)`;
		} else if (rangeDays > 2) {
			return `linear-gradient(to right, ${COL_WEEK_LIGHT} 0%, ${COL_WEEK_LIGHT} 70%, ${COL_TODAY_LIGHT} 70%, ${COL_TODAY_LIGHT} 100%)`;
		}
		return COL_WEEK_LIGHT;
	});

	export function setRange(newStart: number, newEnd: number) {
		if (slider) {
			suppressUpdate = true;
			slider.set([newStart, newEnd]);
			suppressUpdate = false;
		}
	}

	function buildSliderRange(): Options['range'] {
		if (rangeDays > 8) {
			return { 'min': min, '50%': weekStart, '80%': todayStart, 'max': max } as any;
		} else if (rangeDays > 2) {
			return { 'min': min, '70%': todayStart, 'max': max } as any;
		}
		return { min, max };
	}

	function buildPips() {
		if (rangeDays > 8) {
			return {
				mode: PipsMode.Positions as const,
				values: [0, 25, 50, 65, 80, 90, 100],
				density: 100,
				format: {
					to: (v: number) => {
						const d = new Date(v);
						const hoursFromEnd = (max - v) / 3600000;
						if (hoursFromEnd <= 24) {
							const h = d.getUTCHours();
							if (h === 0) return fmtDateShort(d);
							if (h === 6 || h === 12 || h === 18) return h + ':00';
							return '';
						}
						return fmtDateShort(d);
					},
				},
			};
		} else if (rangeDays > 2) {
			return {
				mode: PipsMode.Positions as const,
				values: [0, 20, 40, 60, 85, 100],
				density: 100,
				format: {
					to: (v: number) => {
						const d = new Date(v);
						const hoursFromEnd = (max - v) / 3600000;
						if (hoursFromEnd <= 24) {
							const h = d.getUTCHours();
							if (h === 0) return fmtDateShort(d);
							if (h === 12) return '12:00';
							return '';
						}
						return fmtDateShort(d);
					},
				},
			};
		}
		return {
			mode: PipsMode.Count as const,
			values: 6,
			density: 100,
			format: {
				to: (v: number) => {
					const d = new Date(v);
					if (rangeDays < 1) return d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' });
					return fmtDateShort(d);
				},
			},
		};
	}

	function fmtDateShort(d: Date): string {
		const opts: Intl.DateTimeFormatOptions = { month: 'short', day: 'numeric', timeZone: 'UTC' };
		if (d.getUTCFullYear() !== new Date().getUTCFullYear()) opts.year = 'numeric';
		return d.toLocaleDateString('en-US', opts);
	}

	function fmtDateTimeFull(v: number): string {
		return new Date(v).toLocaleString('en-US', {
			month: 'short', day: 'numeric', year: 'numeric',
			hour: '2-digit', minute: '2-digit',
			timeZone: 'UTC',
		});
	}

	function initSlider() {
		if (slider) slider.destroy();
		if (!el || min >= max) return;

		if (!start) start = Math.max(min, max - 604800000);
		if (!end) end = max;

		noUiSlider.create(el, {
			start: [start, end],
			connect: true,
			range: buildSliderRange(),
			step: 600000,
			tooltips: [
				{ to: (v: number) => fmtDateTimeFull(v) },
				{ to: (v: number) => fmtDateTimeFull(v) },
			],
			pips: buildPips(),
		});

		slider = (el as any).noUiSlider!;
		slider!.on('change', (values: (string | number)[]) => {
			if (suppressUpdate) return;
			start = Number(values[0]);
			end = Number(values[1]);
			onchange?.(start, end);
		});
		slider!.on('update', () => requestAnimationFrame(clampTooltips));
	}

	function clampTooltips() {
		const container = el?.parentElement;
		if (!container) return;
		const bounds = container.getBoundingClientRect();
		container.querySelectorAll<HTMLElement>('.noUi-tooltip').forEach((tt) => {
			tt.style.transform = 'translate(-50%, 0)';
			const r = tt.getBoundingClientRect();
			if (r.left < bounds.left) {
				tt.style.transform = `translate(calc(-50% + ${bounds.left - r.left}px), 0)`;
			} else if (r.right > bounds.right) {
				tt.style.transform = `translate(calc(-50% - ${r.right - bounds.right}px), 0)`;
			}
		});
	}

	$effect(() => { if (el && min < max) initSlider(); });

	$effect(() => {
		if (slider && start && end) {
			const cur = slider.get() as string[];
			if (Math.abs(Number(cur[0]) - start) > 1000 || Math.abs(Number(cur[1]) - end) > 1000) {
				suppressUpdate = true;
				slider.set([start, end]);
				suppressUpdate = false;
			}
		}
	});

	onDestroy(() => slider?.destroy());
</script>

<div class="slider-container" style:--track-bg={trackGradient}>
	<div bind:this={el} class="slider-track"></div>
	<div class="zone-labels">
		{#each zones as zone}
			<div class="zone-label" style="width:{zone.width};color:{zone.color}">{zone.label}</div>
		{/each}
	</div>
</div>

<style>
	.slider-container {
		padding: 0 8px;
	}
	.slider-track {
		height: 14px;
	}
	/* Track background uses zone gradient — !important to override noUiSlider defaults */
	.slider-track :global(.noUi-target) {
		background: var(--track-bg) !important;
		border: none !important;
		border-radius: 7px !important;
		box-shadow: none !important;
		height: 14px !important;
	}
	.slider-track :global(.noUi-base) {
		border-radius: 7px !important;
	}
	/* Selected range darkens the underlying track */
	.slider-track :global(.noUi-connect) {
		background: rgba(0,0,0,0.18) !important;
		border-radius: 7px !important;
	}
	/* Handles */
	.slider-track :global(.noUi-handle) {
		width: 20px !important;
		height: 20px !important;
		border-radius: 50% !important;
		top: -4px !important;
		right: -10px !important;
		border: 2.5px solid var(--color-brand-primary, #1F4E79) !important;
		background: white !important;
		box-shadow: 0 1px 4px rgba(0,0,0,0.25) !important;
		cursor: grab !important;
	}
	.slider-track :global(.noUi-handle::before),
	.slider-track :global(.noUi-handle::after) {
		display: none !important;
	}
	/* Tooltips below handles */
	.slider-track :global(.noUi-tooltip) {
		font-size: 10px;
		padding: 2px 6px;
		border: 1px solid var(--color-brand-divider, #E2E5EA);
		background: white;
		color: var(--color-brand-text, #1B2330);
		border-radius: 4px;
		bottom: auto !important;
		top: 140% !important;
	}
	/* Pips */
	.slider-track :global(.noUi-pips) {
		height: 20px;
		padding: 0;
		top: 100%;
	}
	.slider-track :global(.noUi-marker) {
		background: rgba(0,0,0,0.12);
	}
	.slider-track :global(.noUi-value) {
		font-size: 9px;
		color: var(--color-brand-textMuted, #5A6472);
		top: 8px;
	}
	/* Zone labels */
	.zone-labels {
		display: flex;
		margin-top: 24px;
	}
	.zone-label {
		font-size: 10px;
		font-weight: 600;
		text-align: center;
	}
</style>
