// src/admin/resources/sites/dialogs/CalibrateDialog.tsx
import React, { useState } from 'react';
import { useCreate, useNotify, useRefresh } from 'react-admin';
import {
    Button,
    CircularProgress,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    TextField,
} from '@mui/material';

interface CalibrateDialogProps {
    open: boolean;
    onClose: () => void;
    sensorId: string;
    sensorSerial: string;
}

export const CalibrateDialog: React.FC<CalibrateDialogProps> = ({
    open,
    onClose,
    sensorId,
    sensorSerial,
}) => {
    const [create, { isPending }] = useCreate();
    const notify = useNotify();
    const refresh = useRefresh();

    const [slope, setSlope] = useState('1');
    const [intercept, setIntercept] = useState('0');
    const [validFrom, setValidFrom] = useState(new Date().toISOString().slice(0, 16));
    const [performedBy, setPerformedBy] = useState('');
    const [notes, setNotes] = useState('');

    const handleSubmit = () => {
        create(
            'sensor_calibrations',
            {
                data: {
                    sensor_id: sensorId,
                    slope: parseFloat(slope),
                    intercept: parseFloat(intercept),
                    valid_from: new Date(validFrom).toISOString(),
                    performed_by: performedBy || null,
                    notes: notes || null,
                },
            },
            {
                onSuccess: () => {
                    notify('Calibration created', { type: 'success' });
                    refresh();
                    onClose();
                },
                onError: () => {
                    notify('Failed to create calibration', { type: 'error' });
                },
            },
        );
    };

    return (
        <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
            <DialogTitle>Calibrate Sensor: {sensorSerial}</DialogTitle>
            <DialogContent sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 1 }}>
                <TextField
                    label="Slope"
                    type="number"
                    value={slope}
                    onChange={(e) => setSlope(e.target.value)}
                    inputProps={{ step: 'any' }}
                    fullWidth
                />
                <TextField
                    label="Intercept"
                    type="number"
                    value={intercept}
                    onChange={(e) => setIntercept(e.target.value)}
                    inputProps={{ step: 'any' }}
                    fullWidth
                />
                <TextField
                    label="Valid From"
                    type="datetime-local"
                    value={validFrom}
                    onChange={(e) => setValidFrom(e.target.value)}
                    fullWidth
                    slotProps={{ inputLabel: { shrink: true } }}
                />
                <TextField
                    label="Performed By"
                    value={performedBy}
                    onChange={(e) => setPerformedBy(e.target.value)}
                    fullWidth
                />
                <TextField
                    label="Notes"
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    multiline
                    rows={2}
                    fullWidth
                />
            </DialogContent>
            <DialogActions>
                <Button onClick={onClose} disabled={isPending}>
                    Cancel
                </Button>
                <Button
                    onClick={handleSubmit}
                    variant="contained"
                    disabled={isPending}
                    startIcon={isPending ? <CircularProgress size={16} /> : undefined}
                >
                    Save Calibration
                </Button>
            </DialogActions>
        </Dialog>
    );
};

// src/lib/components/dialogs/CalibrateDialog.svelte
<script lang="ts">
	import { api } from '$api/crud';
	import { recalibrateCalibration } from '$api/service';
	import { toastStore } from '$lib/stores/toast.svelte';
	import Dialog from '$components/ui/Dialog.svelte';

	let {
		open = $bindable(false),
		sensorId,
		sensorName,
		onsuccess,
	}: {
		open: boolean;
		sensorId: string;
		sensorName: string;
		onsuccess?: () => void;
	} = $props();

	let slope = $state('1.0');
	let intercept = $state('0.0');
	let validFrom = $state(new Date().toISOString().slice(0, 16));
	let notes = $state('');
	let saving = $state(false);

	async function handleSave() {
		saving = true;
		try {
			const cal = await api.sensorCalibrations.create({
				sensor_id: sensorId,
				slope: Number(slope),
				intercept: Number(intercept),
				valid_from: new Date(validFrom).toISOString(),
				notes: notes || undefined,
			});
			await recalibrateCalibration((cal as { id: string }).id);
			toastStore.success('Calibration saved and recalculation triggered');
			open = false;
			onsuccess?.();
		} catch (e) {
			toastStore.error(e instanceof Error ? e.message : 'Calibration failed');
		} finally { saving = false; }
	}
</script>

<Dialog bind:open title="Calibrate {sensorName}" maxWidth="sm">
	{#snippet children()}
		<div class="space-y-3">
			<div class="grid grid-cols-2 gap-3">
				<div class="flex flex-col gap-1">
					<label for="slope" class="text-sm font-medium">Slope</label>
					<input id="slope" type="number" step="any" bind:value={slope} class="px-3 py-1.5 border border-brand-divider rounded-md bg-brand-surface text-sm" />
				</div>
				<div class="flex flex-col gap-1">
					<label for="intercept" class="text-sm font-medium">Intercept</label>
					<input id="intercept" type="number" step="any" bind:value={intercept} class="px-3 py-1.5 border border-brand-divider rounded-md bg-brand-surface text-sm" />
				</div>
			</div>
			<div class="flex flex-col gap-1">
				<label for="valid" class="text-sm font-medium">Valid From</label>
				<input id="valid" type="datetime-local" bind:value={validFrom} class="px-3 py-1.5 border border-brand-divider rounded-md bg-brand-surface text-sm" />
			</div>
			<div class="text-xs text-brand-muted font-mono">y = {slope}x + {intercept}</div>
			<div class="flex flex-col gap-1">
				<label for="notes" class="text-sm font-medium">Notes</label>
				<textarea id="notes" bind:value={notes} rows="2" class="px-3 py-1.5 border border-brand-divider rounded-md bg-brand-surface text-sm"></textarea>
			</div>
		</div>
	{/snippet}
	{#snippet actions()}
		<button onclick={() => open = false} class="px-3 py-1.5 border border-brand-divider rounded-md text-sm cursor-pointer bg-brand-surface">Cancel</button>
		<button onclick={handleSave} disabled={saving} class="px-3 py-1.5 bg-brand-primary text-white rounded-md text-sm cursor-pointer border-none disabled:opacity-50">{saving ? 'Saving...' : 'Save & Recalculate'}</button>
	{/snippet}
</Dialog>
